version: '3.8'
services:
  database:
    image: mongo:latest
    container_name: database-iot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-iot
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongodb_data:
  redis-data: